version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:80"
    container_name: tasklogix 
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network

networks:
  my_network:
